name: openff-force-fields

channels:
  - simonboothroyd
  - openeye
  - conda-forge
  - defaults

dependencies:

  - python
  - pip

  - openeye-toolkits

  # Common dependencies
  - tqdm
  - seaborn

  # MNSol data curation
  - xlrd

  # vdW fitting
  - nonbonded >= 0.0.1b1
  - openmm >=7.5.1
  - distributed ==2.30.1
  - mdtraj ==1.9.4

  # QM fitting
  - pyyaml
  - qcportal
  - torsiondrive
  - qcelemental
  - cachetools
  - chemper
  - geometric
  - cachetools

  # Transfer free energies
  - requests-mock

  # Relative binding free energies
  - perses
  - plotly
  - scikit-learn

  # QC benchmarks
  - openmmforcefields

  - pip:
      - git+git://github.com/openforcefield/openff-qcsubmit.git@main
      - git+git://github.com/openforcefield/bespoke-fit.git@main
      - git+git://github.com/openforcefield/openff-arsenic.git@13129d8
